# Generated by Django 5.2.1 on 2025-05-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceexpert',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
