# Generated by Django 5.2.1 on 2025-05-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceexpert_options'),
        ('student', '0002_maintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='services.serviceexpert'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='expert_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='work_in_progress_image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_progress/'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
