# Generated by Django 5.2.1 on 2025-05-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_maintenancerequest_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='service_type',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('carpentry', 'Carpentry'), ('general', 'General Maintenance')], default='general', help_text='Type of service required', max_length=20),
        ),
    ]
