# Generated by Django 5.2.1 on 2025-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_maintenancerequest_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='service_type',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC/Air Conditioning'), ('carpentry', 'Carpentry'), ('general', 'General Maintenance'), ('cleaning', 'Cleaning'), ('security', 'Security Systems')], default='general', help_text='Type of service required', max_length=20),
        ),
    ]
